config/routes.rb
Rails.application.routes.draw do
  resources :relacionamentos, only: [:index, :show, :create, :destroy]
  resources :tags, only: [:index]
  get 'tags/:texto', to: 'tags#show'
  resources :tweets, except: [:new, :edit, :update] do
    resources :likes, only: [:create, :destroy]
    resources :comentarios, except: [:index]
  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }


  root to: 'tweets#index'

end

app/models/comentario.rb
class Comentario < ApplicationRecord

  belongs_to :tweet
  belongs_to :user

  validates_presence_of :texto

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new(tweet_id: params[:tweet_id])
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = current_user.comentarios.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to tweet_path(@comentario.tweet), notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to tweet_path(@comentario.tweet), notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to tweet_path(@comentario.tweet), notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario

      @comentario = Comentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:texto, :tweet_id, :user_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.slim
= form_for  @comentario, url: tweet_comentarios_path(), method: :post  do |f|
  - if @comentario.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comentario.errors.count, "error")} prohibited this comentario from being saved:"
      ul
        - @comentario.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :texto
    = f.text_field :texto
    = f.hidden_field :tweet_id, :value => params[:tweet_id]

  .actions = f.submit

app/views/comentarios/edit.html.slim
h1 Editing comentario

== render 'form'


=< link_to 'Back', tweet_path(@comentario.tweet)

app/views/comentarios/new.html.slim
h1 New comentario

== render 'form'

= link_to 'Back', tweet_path(params[:tweet_id])

app/views/comentarios/show.html.slim
p#notice = notice

p
  strong Comentario:
  = @comentario.comentario
p
  strong Tweet:
  = @comentario.tweet
p
  strong User:
  = @comentario.user

=> link_to 'Edit', edit_comentario_path(@comentario)
'|
=< link_to 'Back', comentarios_path