config/routes.rb
Rails.application.routes.draw do
  resources :relacionamentos, only: [:index, :show, :create, :destroy]
  resources :tags, only: [:index]
  get 'tags/:texto', to: 'tags#show'
  resources :tweets, except: [:new, :edit, :update] do
    resources :likes, only: [:create, :destroy]
    resources :comentarios, except: [:index]
  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }


  root to: 'tweets#index'

end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_many :tag_tweets, dependent: :destroy
  has_many :tags, through: :tag_tweets

  has_many :likes, dependent: :destroy
  has_many :comentarios, dependent: :destroy

  belongs_to :user

  validates_presence_of :texto

  after_create do
    tweet = Tweet.find(self.id)
    hashtags = tweet.texto.scan(/#\w+\b/)
    unless hashtags == []
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_initialize_by(texto: hashtag.downcase.delete('#'))
        tweet.tags << tag
      end
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [ :show, :destroy ]
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
    @tags = Tag.all
    @usuarios = User.all
      #@tweets = current_user.feed.order("created_at DESC")
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :index, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comentarios = Comentario.where(tweet_id: @tweet.id)
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_path, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:texto, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_com_tags texto
    texto.gsub(/#\w+\b/){|tag| link_to tag, "/tags/#{tag.delete('#')}"}.html_safe
  end
end

app/views/tweets/_form.html.slim
= form_with(model: tweet, local: true) do |f|
  - if tweet.errors.any?
    #error_explanation
      h2 = "#{pluralize(tweet.errors.count, "error")} prohibited this tweet from being saved:"
      ul
        - tweet.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.text_field :texto, class: "form-control", :required =>true

  .form-group
    = f.submit do
      span.icon
        i.fa.fa-eye aria-hidden="true"

app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

=> link_to 'Show', @tweet
'|
=< link_to 'Back', tweets_path

app/views/tweets/index.html.slim
br
br
.row
  .col-2
    h3 trending
    - @tags.each do |tag|
      p
        = tags_com_link tag.texto
  .col-6
    == render 'form', tweet: @tweet
    br
    - @tweets.each do |tweet|
      .card
        .card-header
          strong= "@#{tweet.user.nome_ou_usuario}"

        .card-body
          = tweet_com_tags tweet.texto

          div
            - if user_signed_in? && current_user.id == tweet.user_id
              = link_to tweet, class: "level-item" do
                span.icon
                  i.fa.fa-eye aria-hidden="true"
              = link_to tweet, method: :delete, data: {confirm: "Tem certeza que deseja deletar tweeet?"} do
                span.icon
                  i.fas.fa-trash-alt aria-hidden="true"
      br

  .col
    h3 Usuarios
    - @usuarios.each do |usuario|
      p
        = link_to "@#{usuario.nome_ou_usuario}", relacionamento_path(usuario)

app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.slim
p#notice = notice
p =< link_to 'Back', tweets_path
strong= "@#{@tweet.user.nome_ou_usuario}"
p
  strong   = tweet_com_tags @tweet.texto

- pre_like = @tweet.likes.find { |like| like.user_id == current_user.id}
- if pre_like
  = link_to tweet_like_path(@tweet, pre_like), method: :delete do
    i.fas.fa-heart
- else
  = link_to tweet_likes_path(@tweet), method: :post do
    i.far.fa-heart


p
  = link_to 'Novo Comentrario', new_tweet_comentario_path(tweet_id: @tweet.id)
div
 -unless @comentarios.empty?
   - @comentarios.each do |comentario|
     .card
       .card-body
         p = comentario.texto
         - if user_signed_in? && current_user.id == @tweet.user_id
           p
             = link_to  tweet_comentario_path(id: comentario.id, tweet_id: @tweet.id), data: {confirm: 'Tem certeza?'}, method: :delete do
               span.icon
                 i.fas.fa-trash-alt aria-hidden="true"