config/routes.rb
Rails.application.routes.draw do
  resources :relacionamentos, only: [:index, :show, :create, :destroy]
  resources :tags, only: [:index]
  get 'tags/:texto', to: 'tags#show'
  resources :tweets, except: [:new, :edit, :update] do
    resources :likes, only: [:create, :destroy]
    resources :comentarios, except: [:index]
  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }


  root to: 'tweets#index'

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_tweets
  has_many :tweets, through:  :tag_tweets

  validates_presence_of :texto

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find_by(texto: params[:texto])
    @tweets = @tag.tweets
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def tags_com_link texto
    texto.gsub(/#\w+\b/){|tag| link_to tag, "/tags/#{tag.delete('#')}"}.html_safe
  end
end

app/views/tags/_form.html.slim
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :texto
    = f.text_field :texto
  .field
    = f.label :tweet
    = f.text_field :tweet
  .actions = f.submit

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

=> link_to 'Show', @tag
'|
=< link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Texto
      th Tweet
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.texto
        td = tag.tweet
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Texto:
  = @tag.texto
-@tag.tweets.each do |tweet|
  p
    strong Tweet:
    = tweet.texto