config/routes.rb
Rails.application.routes.draw do
  resources :relacionamentos, only: [:index, :show, :create, :destroy]
  resources :tags, only: [:index]
  get 'tags/:texto', to: 'tags#show'
  resources :tweets, except: [:new, :edit, :update] do
    resources :likes, only: [:create, :destroy]
    resources :comentarios, except: [:index]
  end

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }


  root to: 'tweets#index'

end

app/models/relacionamento.rb
class Relacionamento < ApplicationRecord

  belongs_to :seguidor, class_name: 'User'
  belongs_to :seguido, class_name: 'User'

end

app/controllers/relacionamentos_controller.rb
class RelacionamentosController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    usuario = User.find(params[:seguido_id])
    current_user.seguir(usuario)
    redirect_to root_path
  end

  def destroy
    current_user.deixar_de_seguir(params[:id])
    redirect_to root_path
  end

end

app/helpers/relacionamentos_helper.rb
module RelacionamentosHelper
end

app/views/relacionamentos/_form.html.slim
= form_for @relacionamento do |f|
  - if @relacionamento.errors.any?
    #error_explanation
      h2 = "#{pluralize(@relacionamento.errors.count, "error")} prohibited this relacionamento from being saved:"
      ul
        - @relacionamento.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :seguidor
    = f.text_field :seguidor
  .field
    = f.label :seguido
    = f.text_field :seguido
  .actions = f.submit

app/views/relacionamentos/edit.html.slim
h1 Editing relacionamento

== render 'form'

=> link_to 'Show', @relacionamento
'|
=< link_to 'Back', relacionamentos_path

app/views/relacionamentos/index.html.slim
h1 Listing relacionamentos

/! ocultar caso seja o proprio usuario
- @users.each do |user|
  - unless current_user == user
    /! seguir
    - unless current_user.seguindo?(user)
      p
        = user.username
      = form_for(current_user.seguidor_relacionamentos.build) do |f|
        div= hidden_field_tag :seguido_id, user.id
        = f.submit "Seguir", class: "btn btn-primary my-button"
    /! deixar de seguir
    = link_to 'Deixar de Seguir', relacionamento_path(user), method: :delete, class: "btn btn-danger" if current_user.seguindo?(user)

app/views/relacionamentos/new.html.slim
h1 New relacionamento

== render 'form'

= link_to 'Back', relacionamentos_path

app/views/relacionamentos/show.html.slim
p#notice = notice

h3 = "@#{@user.nome_ou_usuario}"
- unless current_user == @user
  /! seguir
  - unless current_user.seguindo?(@user)
    p
      = @user.username
    = form_for(current_user.seguidor_relacionamentos.build) do |f|
      div= hidden_field_tag :seguido_id, @user.id
      = f.submit "Seguir", class: "btn btn-primary my-button"
  /! deixar de seguir
  = link_to 'Deixar de Seguir', relacionamento_path(@user), method: :delete, class: "btn btn-danger" if current_user.seguindo?(@user)

- if current_user == @user && !@user.seguidors.empty?
  - @user.seguidors.each do |seguidor|
    = link_to "@#{seguidor.nome_ou_usuario}", relacionamento_path(seguidor)